### ISSUE TITLE
Deprecated functions in 7: Evict with Crux – The secret mission.

### ISSUE THREAD

**Issue by mchughs** [crux-labs/crux-tutorial#1]
In the 7th tutorial page, there is some sample code which will not run with the latest version of crux.

```clojure
(crux/history-descending (crux/db crux)
                           (crux/new-snapshot (crux/db crux))
                           :person/kaarlang)
```

Neither `crux.api/history-descending` nor `crux.api/new-snapshot` seem to exist anymore.

A defined function also uses some old syntax
```clojure
(defn full-query
  [node]
  (crux/q
   (crux/db node)
   '{:find [id]
     :where [[e :crux.db/id id]]
     :full-results? true}))
```
You will get the following error if you try to evaluate the function above
```clojure
; Execution error (IllegalArgumentException) at crux.error/illegal-arg (error.clj:12).
; `full-results?` was removed - use 'pull' instead: https://opencrux.com/reference/queries.html#pull
```
---
`crux.api/entity-history` may be the latest equivalent to `crux.api/history-descending`? Maybe we can just update the example to use this instead.

And I believe 
```clojure
(defn full-query
  [node]
  (crux/q
   (crux/db node)
   '{:find [(pull id [*])]
     :where [[e :crux.db/id id]]
     }))
```
is the `pull` equivalent of `full-results?`

**Comment by deobald** [comment]
Fixed in https://github.com/crux-labs/crux-tutorial/commit/fd95f1ddc16be0f895535efdf654ae49893bc937 

@mchughs Thanks for the report! 🙏
